# Generated by Django 4.1.5 on 2023-01-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(default=0, help_text='The subscriber ID from the Newsletter plugin')),
                ('send_dt', models.DateTimeField()),
                ('open_dt', models.DateTimeField()),
                ('opened', models.BooleanField(default=False, help_text='Was this email opened by the recipient.', verbose_name='Vai epasts atvērts?')),
            ],
        ),
    ]
