on:
  push:
    branches:
      - develop

name: Deploy develop branch code
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code from develop branch
      uses: actions/checkout@v3

    - name: Sync files to hosted dev
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      env:
        django_secret_key : ${{ secrets.DJANGO_SECRET_KEY_PROD }}
        mongodb_uri : ${{ secrets.mongodb_uri }}
      with:
        server: ftp.saknes.area.lv
        username: ${{ secrets.FTP_DEV_USERNAME }}
        password: ${{ secrets.FTP_DEV_PASSWORD }}
